import Head from 'next/head'
import {Navbar} from "../components";
import {client} from "../lib/sanity/config";
import {queries} from "../constants";
import Header from "../components/header/Header";
import About from "../components/about/About";
import Work from "../components/work/Work";
import Skills from "../components/skills/Skills";
import Contact from "../components/contact/Contact";

export interface ISSRProps {
    abouts: {status: string, value: SanityDoc.Abouts[]},
    works: {status: string, value: SanityDoc.Works[]},
    skills: {status: string, value: SanityDoc.Skills[]},
}

const Home = ({abouts, works, skills}: ISSRProps) => {
    return (
        <div className={'w-full h-full bg-white'}>
            <Head>
                <title>Osida Richards V2</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar/>
            <main>
                <Header/>
                <About data={abouts.value}/>
                <Work data={works.value}/>
                <Skills data={skills.value}/>
            </main>
            <Contact/>
        </div>
    )
}

export default Home

export async function getServerSideProps() {
    try {
        const [abouts, works, skills] = await Promise.allSettled([
            client(process.env.SANITY_TOKEN).fetch(queries.sanity.abouts).then(res => JSON.parse(JSON.stringify(res))),
            client(process.env.SANITY_TOKEN).fetch(queries.sanity.works).then(res => JSON.parse(JSON.stringify(res))),
            client(process.env.SANITY_TOKEN).fetch(queries.sanity.skills).then(res => JSON.parse(JSON.stringify(res)))
        ])
        return {
            props: {
                abouts,
                works,
                skills,
            },
        }
    } catch (e) {
        console.log('getServerSideProps error.')
        console.log(JSON.parse(JSON.stringify(e)))
    }

    return {
        props: {},
    }
}